In [1]:
## import nba_api to collect information
from nba_api.stats import endpoints
from nba_api.stats.static import teams 
teams = teams.get_teams()

## other pacakges used
import pandas as pd

In [2]:
## List of team ids to use for the purposes of this analysis. teams dataframe as a list of all teams and their IDs used for the api
team_list = ['1610612747','1610612738','1610612741']
#'1610612747' - Lakers,'1610612738' - Celtics,'1610612741' - Bulls
#team_list

In [3]:
## Testing
#data = endpoints.teamyearbyyearstats.TeamYearByYearStats(team_id='1610612738')
#df = data.get_data_frames()[0]
#df_info = df[['TEAM_ID','TEAM_NAME','YEAR','NBA_FINALS_APPEARANCE','FGM','FGA','FG_PCT','FG3M','FG3A','FG3_PCT','FTM','FTA','FT_PCT','OREB','DREB','REB','AST','PF','STL','TOV','BLK']]
#df_info = df_info[df.FGA > 0]

In [4]:
## Create for loop to obtain information from api by team
team_data = pd.DataFrame()

for x in team_list:
    data = endpoints.teamyearbyyearstats.TeamYearByYearStats(team_id=x)
    df = data.get_data_frames()[0]
    
    if len(team_data.columns) == 0:
        team_data = df
    else:
        team_data = team_data.append(df)

In [5]:
## Data cleansing process

#only use selected columns from data set
team_data = team_data[['TEAM_ID','TEAM_NAME','NBA_FINALS_APPEARANCE','FGM','FGA','FG_PCT','FG3M','FG3A','FG3_PCT','FTM','FTA','FT_PCT','OREB','DREB','REB','AST','PF','STL','TOV','BLK']]

#clean data set so that only data is used when FGA information is captured
team_data = team_data[team_data.FGA > 0]

#create column taht indicates in team won championship or not. 1 = champions
team_data['CHAMPION'] = team_data['NBA_FINALS_APPEARANCE'].apply(lambda x: 1 if x == 'LEAGUE CHAMPION' else 0)

#drop NBA_FINALS_APPEARANCE column as not used
team_data.drop(columns=['NBA_FINALS_APPEARANCE'], inplace=True)

In [6]:
#data frame with data to use for machine learning
team_data

,TEAM_ID,TEAM_NAME,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,PF,STL,TOV,BLK,CHAMPION
34,1610612747,Lakers,3964,7512,0.528,10,96,0.104,1495,2031,0.736,1235,2433,3668,2519,1931,844,1584,479,0
35,1610612747,Lakers,3854,7250,0.532,58,226,0.257,1712,2272,0.754,1095,2499,3594,2455,2054,726,1578,478,0
36,1610612747,Lakers,3952,7254,0.545,90,295,0.305,1702,2232,0.763,1063,2550,3613,2575,1931,695,1537,481,1
37,1610612747,Lakers,3834,7343,0.522,138,409,0.337,1812,2329,0.778,1101,2555,3656,2433,2031,693,1467,419,0
38,1610612747,Lakers,3740,7245,0.516,164,447,0.367,2012,2550,0.789,1127,2515,3642,2428,1853,728,1358,482,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50,1610612741,Bulls,3169,7141,0.444,623,1831,0.340,1474,1848,0.798,999,2797,3796,1851,1455,643,1112,393,0
51,1610612741,Bulls,3170,7285,0.435,906,2549,0.355,1194,1574,0.759,790,2872,3662,1923,1571,626,1147,289,0
52,1610612741,Bulls,3266,7205,0.453,745,2123,0.351,1328,1695,0.783,718,2799,3517,1796,1663,603,1159,351,0
53,1610612741,Bulls,2573,5762,0.447,793,2282,0.348,1006,1332,0.755,680,2041,2721,1510,1417,652,1005,265,0
54,1610612741,Bulls,3035,6380,0.476,904,2446,0.370,995,1258,0.791,693,2544,3237,1927,1362,482,1089,304,0